/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TerrainRangesEditor.java
 *
 * Created on Mar 28, 2012, 5:53:35 PM
 */
package org.pepsoft.worldpainter.terrainRanges;

import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Window;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import org.pepsoft.worldpainter.HeightMapTileFactory;
import org.pepsoft.worldpainter.Terrain;

/**
 *
 * @author pepijn
 */
public class HeightMapTileFactoryEditor extends javax.swing.JPanel implements ButtonPressListener {
    /** Creates new form TerrainRangesEditor */
    public HeightMapTileFactoryEditor() {
        initComponents();
    }
    
    public boolean save() {
        if (tableModel == null) {
            return true;
        }
        if (! tableModel.isValid()) {
            JOptionPane.showMessageDialog(this, "You have configured multiple terrain types with the same levels!\nRemove, or change the level of, one of the duplicates.", "Duplicate Levels", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        tileFactory.setTerrainRanges(tableModel.getTerrainRanges());
        tileFactory.setRandomise(checkBoxRandomise.isSelected());
        boolean beaches = checkBoxBeaches.isSelected();
        tileFactory.setBeaches(beaches);
        if (beaches) {
            tileFactory.setWaterHeight(((Number) spinnerWaterLevel.getValue()).intValue());
        }
        return true;
    }

    public HeightMapTileFactory getTileFactory() {
        return tileFactory;
    }

    public void setTileFactory(HeightMapTileFactory tileFactory) {
        this.tileFactory = tileFactory;
        if (tileFactory != null) {
            tableModel = new TerrainRangesTableModel(tileFactory.getTerrainRanges());
            jTable1.setModel(tableModel);
            
            jTable1.setDefaultRenderer(Integer.class, new DefaultTableCellRenderer());
            jTable1.setDefaultRenderer(Terrain.class, new TerrainTableCellRenderer());
            jTable1.setDefaultRenderer(JButton.class, new JButtonTableCellRenderer());
            
            jTable1.setDefaultEditor(Integer.class, new JSpinnerTableCellEditor(new SpinnerNumberModel(1, 1, tileFactory.getMaxHeight() - 1, 1)));
            JComboBox terrainEditor = new JComboBox(Terrain.getConfiguredValue());
            terrainEditor.setRenderer(new TerrainListCellRenderer());
            jTable1.setDefaultEditor(Terrain.class, new DefaultCellEditor(terrainEditor));
            jTable1.setDefaultEditor(JButton.class, new JButtonTableCellEditor(this));
            
            checkBoxBeaches.setSelected(tileFactory.isBeaches());
            spinnerWaterLevel.setModel(new SpinnerNumberModel(tileFactory.getWaterHeight(), 0, tileFactory.getMaxHeight() - 1, 1));
            spinnerWaterLevel.setEnabled(checkBoxBeaches.isSelected());
            
            checkBoxRandomise.setSelected(tileFactory.isRandomise());
        }
    }

    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled);
        jTable1.setEnabled(enabled);
        checkBoxBeaches.setEnabled(enabled);
        spinnerWaterLevel.setEnabled(enabled && checkBoxBeaches.isSelected());
        buttonAdd.setEnabled(enabled);
        checkBoxRandomise.setEnabled(enabled);
    }

    // ButtonPressListener

    @Override
    public void buttonPressed(int row, int column) {
        tableModel.deleteRow(row);
    }

    private void addTerrain() {
        Window window = SwingUtilities.getWindowAncestor(this);
        AddTerrainRangeDialog dialog = (window instanceof Frame) ? new AddTerrainRangeDialog((Frame) window, tileFactory.getMaxHeight()) : new AddTerrainRangeDialog((Dialog) window, tileFactory.getMaxHeight());
        dialog.setVisible(true);
        if (! dialog.isCancelled()) {
            tableModel.addRow(dialog.getSelectedLevel(), dialog.getSelectedTerrain());
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonAdd = new javax.swing.JButton();
        checkBoxBeaches = new javax.swing.JCheckBox();
        spinnerWaterLevel = new javax.swing.JSpinner();
        checkBoxRandomise = new javax.swing.JCheckBox();

        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        buttonAdd.setText("Add...");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        checkBoxBeaches.setText("beaches around water level:");
        checkBoxBeaches.setToolTipText("Whether to add beaches from two levels below the water level to two levels above.");
        checkBoxBeaches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxBeachesActionPerformed(evt);
            }
        });

        spinnerWaterLevel.setEnabled(false);

        checkBoxRandomise.setText("noisy edges");
        checkBoxRandomise.setToolTipText("Whether to randomise the edges of the terrain types (except beaches).");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(checkBoxBeaches)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerWaterLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkBoxRandomise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAdd))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdd)
                    .addComponent(checkBoxBeaches)
                    .addComponent(spinnerWaterLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxRandomise)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        addTerrain();
    }//GEN-LAST:event_buttonAddActionPerformed

    private void checkBoxBeachesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxBeachesActionPerformed
        spinnerWaterLevel.setEnabled(checkBoxBeaches.isSelected());
    }//GEN-LAST:event_checkBoxBeachesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JCheckBox checkBoxBeaches;
    private javax.swing.JCheckBox checkBoxRandomise;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner spinnerWaterLevel;
    // End of variables declaration//GEN-END:variables

    private HeightMapTileFactory tileFactory;
    private TerrainRangesTableModel tableModel;
    
    private static final long serialVersionUID = 1L;
}